### ISSUE TITLE
개발사항 정리

### ISSUE THREAD

**Issue by jaehong-hwang** [kukbaproad/kukbap#3]
추가 하고싶은 개발 사항, 항목들 정리 작업

1. 국밥 계산기
2. 국밥 가게 목록

**Comment by BackGyeHoon** [comment]
**1. 국밥 게산기**
    - 일반적인 국밥 대표가격이 아닌 국밥 종류별로 계산기 구현.

**2. 국밥 가게 목록**
    - 서비스 초기에는 강남구 지역 국밥 가게만 노출. 
    - 차후 업데이트를 통해 지역 확장 예정.

**Comment by jaehong-hwang** [comment]
@BackGyeHoon 해당 서비스가 한 웹페이지로 노출되는 형태로 만들건가요?

**Comment by BackGyeHoon** [comment]
@jaehong-hwang SPA로 가는게 좋을거같은데 다른분들 의견도 들어야할듯여

**Comment by jaehong-hwang** [comment]
아아 그 잘못말씀드린거같은데, 국밥 계산기, 국밥 가게 목록 노출이 하나의 서비스인지 각각의 서비스인지가 궁금했던거에요

**Comment by BackGyeHoon** [comment]
@jaehong-hwang  일단 저는 하나의 서비스로 생각하고 있어요.

**Comment by jaehong-hwang** [comment]
@BackGyeHoon 아하! 알겠습니당 일단 그럼 두가지 기능이 들어간 하나의 서비스인거로
